"""added columns to documents table

Revision ID: aef2bec57612
Revises: d4664eb8ea67
Create Date: 2025-07-08 14:17:32.674867

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aef2bec57612'
down_revision: Union[str, None] = 'd4664eb8ea67'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('uploaded_file_path', sa.String(), nullable=False))
    op.add_column('documents', sa.Column('uploaded_at', sa.DateTime(), nullable=True))
    op.drop_column('documents', 'content')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('content', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('documents', 'uploaded_at')
    op.drop_column('documents', 'uploaded_file_path')
    # ### end Alembic commands ###
